version: '2'
services:
    roulettefilms-app:
        image: roulettefilms
        external_links:
            - roulettefilms-postgresql:postgresql
            - roulettefilms-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/roulettefilms
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    roulettefilms-postgresql:
        extends:
            file: postgresql.yml
            service: roulettefilms-postgresql
    roulettefilms-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: roulettefilms-elasticsearch
