version: '2'
services:
    roulettefilms-elasticsearch:
        container_name: roulettefilms-elasticsearch
        image: elasticsearch:2.4.1
        # volumes:
        #     - ~/volumes/jhipster/roulettefilms/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
